
SELECT USER_NAME, HOUR(START_TIME), COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE TO_DATE(START_TIME) = '2023-05-03'
AND HOUR(START_TIME) >= 19
GROUP BY USER_NAME, HOUR(START_TIME)
ORDER BY COUNT(*) DESC;