
-- check query history from user
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE TO_DATE(START_TIME) = 'date'
AND USER_NAME = 'name';
AND QUERY_TEXT like '%something%';
LIMIT 10;

-- check sessions
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.SESSIONS
WHERE USER_NAME = 'username'
AND TO_DATE(CREATED_ON) = current_date()
LIMIT 10;